/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oems;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sachini
 */
public class Item_Transfer extends javax.swing.JFrame {

    /**
     * Creates new form Item_Transfer
     */
    public Item_Transfer() {
        initComponents();
        show_user();
    
    
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EMS;user=sa;password=4470";
            Connection con = DriverManager.getConnection(url);
            
            Statement pst = con.createStatement(); 
            String query = "select EquipmentID from Equipment_Reg_Table";
             ResultSet rs = pst.executeQuery(query);
             while(rs.next())
                
            {
                jComboBox1Eq_ID.addItem(rs.getString("EquipmentID"));
            }
            
            Statement pst2 = con.createStatement();
            String query2 = "select Location_Name from Location_Reg_Table";
            ResultSet rs2 = pst2.executeQuery(query2);
            while (rs2.next())
           {
               jComboBox2LocName.addItem(rs2.getString("Location_Name"));
           }
          
}       catch (ClassNotFoundException ex) { 
            Logger.getLogger(Item_Transfer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Item_Transfer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public ArrayList<ItemTransferUser>userList1(){
    ArrayList<ItemTransferUser> userList1 = new ArrayList<>();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EMS;user=sa;password=4470";
            Connection con = DriverManager.getConnection(url);
            String query1="SELECT * FROM Item_Transfer_Table";
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(query1);
            ItemTransferUser itemtransferuser;
            while(rs.next()){
                itemtransferuser=new ItemTransferUser(rs.getString("Transfered_Date"),rs.getInt("Equipment_ID"),rs.getString("Location_Name"));
                userList1.add(itemtransferuser);
              
            } 
             }
      catch (Exception e){
             JOptionPane.showMessageDialog(null, e);
    }
      return userList1;
    }
    public void show_user(){
        ArrayList<ItemTransferUser> list = userList1();
        DefaultTableModel model = (DefaultTableModel)Itemtransfertbl.getModel();
        Object[] row = new Object[3];
        for(int i = 0; i<list.size();i++){
            row[0]=list.get(i).getTransfered_Date();
            row[1]=list.get(i).getEquipment_ID();
            row[2]=list.get(i).getLocation_Name();
            model.addRow(row);
        }
    
          
    }    /*
            *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txtsearch = new javax.swing.JTextField();
        txtJobNo = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Txtsearch1 = new javax.swing.JTextField();
        txtJobNo1 = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Btn_save = new javax.swing.JButton();
        Btn_Reset = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1Eq_ID = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2LocName = new javax.swing.JComboBox<>();
        TxtEqID = new javax.swing.JTextField();
        TxtLoNAme = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Itemtransfertbl = new javax.swing.JTable();
        jTextField1Date = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Transffered Item");

        jLabel8.setText("Search");

        txtJobNo.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Job No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(Txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel3)
                .addGap(71, 71, 71)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtJobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel8)
                        .addComponent(Txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("OEMS");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("<-----");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setText("Search");

        Txtsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtsearch1ActionPerformed(evt);
            }
        });
        Txtsearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txtsearch1KeyReleased(evt);
            }
        });

        txtJobNo1.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Job No");

        jButton5.setText("View Repaort");

        Btn_save.setText("Save");
        Btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_saveActionPerformed(evt);
            }
        });

        Btn_Reset.setText("Reset");
        Btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ResetActionPerformed(evt);
            }
        });

        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("Transferred Item");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(Txtsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJobNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(Txtsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(Btn_save)
                        .addComponent(Btn_Reset)
                        .addComponent(btn_Update)
                        .addComponent(btn_delete)
                        .addComponent(jButton5))
                    .addComponent(txtJobNo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });

        jLabel1.setText("Transferred Date");

        jLabel7.setText("Equipment ID");

        jComboBox1Eq_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1Eq_IDActionPerformed(evt);
            }
        });

        jLabel10.setText("Location Name");

        jComboBox2LocName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2LocNameActionPerformed(evt);
            }
        });

        Itemtransfertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transferred date", "Equipment ID", "Location Name"
            }
        ));
        Itemtransfertbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemtransfertblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Itemtransfertbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(jTextField1Date))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtEqID)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1Eq_ID, 0, 237, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TxtLoNAme)
                            .addComponent(jComboBox2LocName, 0, 241, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jComboBox1Eq_ID)
                    .addComponent(jComboBox2LocName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtEqID, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(jTextField1Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtLoNAme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ResetActionPerformed
            TxtEqID.setText("");
            jDateChooser1.setDateFormatString("");
            TxtLoNAme.setText("");
            Txtsearch1.setText("");
            txtJobNo1.setText("");
        
           this.dispose();
           Item_Transfer u = new Item_Transfer();
           u.setVisible(true);  
    }//GEN-LAST:event_Btn_ResetActionPerformed

    private void Btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_saveActionPerformed
 try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EMS;user=sa;password=4470";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into Item_Transfer_Table(Transfered_Date,Equipment_ID,Location_Name)values(?,?,?)";
      
            PreparedStatement pst = con.prepareStatement(query);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(jDateChooser1.getDate());
            pst.setString(1, date);
            pst.setString(2,TxtEqID.getText());
            pst.setString(3,TxtLoNAme.getText());
            
            
             
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)Itemtransfertbl.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "Save sucessfully");

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
        
        TxtEqID.setText("");
        jDateChooser1.setDateFormatString("");
        TxtLoNAme.setText("");
        
        
           this.dispose();
           Item_Transfer u = new Item_Transfer();
           u.setVisible(true);        
    }//GEN-LAST:event_Btn_saveActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
          try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EMS;user=sa;password=4470";
            Connection con = DriverManager.getConnection(url);
            String query = "UPDATE Item_Transfer_Table SET Transfered_Date = ?,Equipment_ID = ?,Location_Name = ? where Job_No = ?";
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(jDateChooser1.getDate());
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, date);
            pst.setString(2,TxtEqID.getText());
            pst.setString(3,TxtLoNAme.getText());
            pst.setString(4,txtJobNo1.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)Itemtransfertbl.getModel();
            model.setRowCount(0);
            show_user(); 
            JOptionPane.showMessageDialog(null, "Update sucessfully");
            
        TxtEqID.setText("");
        TxtLoNAme.setText("");
        jDateChooser1.setDateFormatString("");
        
           }
         catch (Exception e){
             JOptionPane.showMessageDialog(null, e);
             
         
    }//GEN-LAST:event_btn_UpdateActionPerformed
    }
    private void Txtsearch1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txtsearch1KeyReleased
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EMS;user=sa;password=4470";
            Connection con = DriverManager.getConnection(url);
            String sql = "select * from Item_Transfer_Table where Job_No = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, Txtsearch1.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                String setJob_No =rs.getString("Job_No");
                txtJobNo1.setText(setJob_No);
                
                Date setPurchasDate =rs.getDate("Transfered_Date");
                jDateChooser1.setDate(setPurchasDate);
                
                String setEquipment_ID =rs.getString("Equipment_ID");
                TxtEqID.setText(setEquipment_ID);
                
                String setLocation_Name =rs.getString("Location_Name");
                TxtLoNAme.setText(setLocation_Name);
          
            }
             
         }
      catch (Exception e){
             JOptionPane.showMessageDialog(null, e);
    }         
    }//GEN-LAST:event_Txtsearch1KeyReleased

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EMS;user=sa;password=4470";
            Connection con = DriverManager.getConnection(url);
            String query = "DELETE FROM Item_Transfer_Table where Job_No =?";
            
            PreparedStatement pst = con.prepareStatement(query);
 
            pst.setString(1,txtJobNo1.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)Itemtransfertbl.getModel();
            model.setRowCount(0);
            show_user();
            
            JOptionPane.showMessageDialog(null, "Deleted sucessfully");
            
             TxtEqID.setText("");
             TxtLoNAme.setText("");
             jDateChooser1.setDateFormatString("");
    
           this.dispose();
           Item_Transfer u = new Item_Transfer();
           u.setVisible(true); 
        }
        catch (Exception e){
             JOptionPane.showMessageDialog(null, e);
    }  
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void ItemtransfertblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemtransfertblMouseClicked
       int i = Itemtransfertbl.getSelectedRow();
        TableModel model = Itemtransfertbl.getModel();
        jTextField1Date.setText(model.getValueAt(i, 0).toString());
        TxtEqID.setText(model.getValueAt(i, 1).toString());
        TxtLoNAme.setText(model.getValueAt(i, 2).toString());
        
        
        boolean a = Itemtransfertbl.isEditing();
       
        if(a==false){
            JOptionPane.showMessageDialog(null, "You can not edit this table ");
    }     
    }//GEN-LAST:event_ItemtransfertblMouseClicked

    private void jComboBox2LocNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2LocNameActionPerformed
        String selectedValue = jComboBox2LocName.getSelectedItem().toString();

        //How to set this delected value into textField

        TxtLoNAme.setText((selectedValue));
    }//GEN-LAST:event_jComboBox2LocNameActionPerformed

    private void jComboBox1Eq_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1Eq_IDActionPerformed
       String selectedValue = jComboBox1Eq_ID.getSelectedItem().toString();

        //How to set this delected value into textField

        TxtEqID.setText((selectedValue));
    }//GEN-LAST:event_jComboBox1Eq_IDActionPerformed

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void Txtsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtsearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtsearch1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Item_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Item_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Item_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Item_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new Item_Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Reset;
    private javax.swing.JButton Btn_save;
    private javax.swing.JTable Itemtransfertbl;
    private javax.swing.JTextField TxtEqID;
    private javax.swing.JTextField TxtLoNAme;
    private javax.swing.JTextField Txtsearch;
    private javax.swing.JTextField Txtsearch1;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1Eq_ID;
    private javax.swing.JComboBox<String> jComboBox2LocName;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1Date;
    private java.awt.TextField txtJobNo;
    private java.awt.TextField txtJobNo1;
    // End of variables declaration//GEN-END:variables
}
